from .config import Configuration as AttemptGraspWithStaticWristConfiguration
from .script import Script as AttemptGraspWithStaticWristScript
from .phases import AttemptGraspWithStaticWristPhase
from .production import AttemptGraspWithStaticWrist