from .config import Configuration as AttemptGraspWithPuppeteerWristConfiguration
from .script import Script as AttemptGraspWithPuppeteerWristScript
from .production import AttemptGraspWithPuppeteerWrist