
DEFAULT_BROM_DIR = "./brom"
DEFAULT_PLOT_DIR = DEFAULT_BROM_DIR + "/watcher_plots"
DEFAULT_RAW_DATA_DIR = DEFAULT_BROM_DIR + "/watcher_raw_data"
DEFAULT_BROM_MODELS_DIR = DEFAULT_BROM_DIR + "/models"