from importlib import resources as impresources
from pathlib import Path
import pkgutil
import shutil
import subprocess
import tempfile
import typer

import brom_drake

def generate_all_discoverable_docs(
    output_dir: Path,
    package_dir: Path = Path("../src/brom_drake"),
):
    """
    Docstring for generate_all_discoverable_docs
    
    :param output_dir: Place to create the doc file for Sphinx.
    :type output_dir: Path
    :param package_dir: Location of the code we are seeking to document.
    :type package_dir: Path
    """

    # Announce beginning of function
    print(f"Generating docs for package in directory: {package_dir}")

    package_name = package_dir.name

    # Identify all submodules in this package
    canonicalized_modules, submodule_names = [], []
    for _, name, is_pkg in pkgutil.walk_packages([package_dir]):
        # Only do the recursive call if it's a package
        if not is_pkg:
            continue

        # Create the module name as it would appear in imports (i.e., "parent.child.grandchild")
        full_module_path = package_dir / name
        full_module_name = str(full_module_path.relative_to(package_dir.parent)).replace("/", ".")
        canonicalized_modules.append(full_module_name)

        # Also save the simple module name
        submodule_names.append(name)

        print(f"Found submodule: {full_module_name}")
    
    # Identify all files in this package
    # TODO(Kwesi): Implement this, if the above loop does not work

    # Organize modules alphabetically
    canonicalized_modules = sorted(canonicalized_modules, key=str.lower)

    for mod in submodule_names:
        print(f"Generating docs for module: {mod}")
        # typer.run(
        #     [
        #         "sphinx-apidoc",
        #         "-o",
        #         str(output_dir),
        #         "--force",
        #         "--module-first",
        #         "--separate",
        #         mod,
        #     ]
        # )

        # Generate the docs for this module
        generate_all_discoverable_docs(
            output_dir=output_dir / mod,
            package_dir=package_dir / mod,
        )

    # TODO(Kwesi): Implement the actual doc generation logic
    write_rst_file_for_package(
        package_name=package_name,
        output_dir=output_dir,
        submodules=submodule_names,
    )

def write_rst_file_for_package(
    package_name: str,
    output_dir: Path,
    submodules: list[str],
):
    """
    Writes an .rst file that is compatible with
    Sphinx's autodoc and autosummary features, containing:
    - hyperlinks to all submodules in `submodules`, and
    - a summary table of all classes and functions in `module_name`.

    :param module_name: Description
    :type module_name: str
    :param output_dir: Description
    :type output_dir: Path
    :param submodules: Description
    :type submodules: list[str]
    """
    # Create the output directory if it doesn't exist
    if not output_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)

    # Create the .rst file
    rst_file_path = output_dir / f"{package_name}.rst"
    
    # Fix the name of the .rst file 
    # For the overall package (this is important so that the index always points to a clear place)
    if package_name == "brom_drake": 
        rst_file_path = output_dir / f"api.rst"
        
    with open(rst_file_path, "w") as rst_file:
        # Write the module title
        title = package_name
        if package_name == "brom_drake":
            # The title for the "overall" page should be API, not brom_drake
            title = "API"

        rst_file.write(f"{title}\n")
        rst_file.write("=" * len(title) + "\n\n")

        # Write the list of submodules
        rst_file.write("Submodules\n")
        rst_file.write("----------\n\n")

        for submodule in sorted(submodules, key=str.lower):
            rst_file.write(f"- `{submodule} <{submodule}/{submodule}.html>`_\n")
        rst_file.write("\n")

        # Write hyperlinks to submodules
        rst_file.write(".. toctree::\n")
        rst_file.write("   :maxdepth: 2\n\n")
        for submodule in submodules:
            rst_file.write(f"   {submodule}\n")
        rst_file.write("\n")

        # # Write autosummary table
        # rst_file.write(".. autosummary::\n")
        # rst_file.write("   :toctree: generated\n\n")
        # rst_file.write(f"   {package_name}.*\n")

    print(f"Wrote RST file for module {package_name} at:")
    print(f"- {rst_file_path}")

def main(output_dir: Path = Path("source"), clean_up_afterward: bool = False):
    # Create directory for storing all of the "autogenerated"
    # docs
    generated_file_dir = output_dir / "generated"
    if not generated_file_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)

    # Create all docs using a recursive function
    generate_all_discoverable_docs(
        output_dir=generated_file_dir,
        package_dir=impresources.files(brom_drake),
    )

    # Build the docs using sphinx-build
    subprocess.run(
        [
            "make",
            "html",
        ]
    )

    print("Completed generating the documentation using sphinx.")

    # Clean Up "temporary directory"
    if clean_up_afterward:
        shutil.rmtree(generated_file_dir)
        print("- Removed temporary directory")

    # subprocess.run(
    #     [
    #         "sphinx-build",
    #         "-M",
    #         "html",
    #         str(output_dir),
    #         "../build/html",
    #     ],
    #     check=True,
    # )

if __name__ == "__main__":
    typer.run(main)